export type Item = {
    id: string
    Name: string,
    Description: string,
    Type: string,
    Element: string,
    File: string,
    Link: string,
    Icon: string,
    Equipment: string | "Weapon" | "co" | "ar" | "ba" | "he" | "pe" | "am"
    Level: number,
    DPS: number,
    Rarity: number,
    Quantity: number,
    Stack: number,
    Cost: number,
    Silver: boolean,
    Gold: boolean,
    Sell: boolean,
    Temporary: boolean,
    Upgrade: boolean,
    Staff: boolean,
    EnhID: number,
    FactionID: number,
    TitleID: number,
    ReqReputation: number,
    ReqClassID: number,
    ReqClassPoints: number,
    ReqTrackQuest: string,
    Meta: string,
}